server:
  port: 8081

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092

order:
  supported-currencies: BRL,USD,EUR

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [cid=%X{correlationId}]"
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG

