server:
  port: 8081

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092

o2c:
  kafka:
    topics:
      order-events: ${O2C_ORDER_EVENTS_TOPIC:o2c.order.v1}

order:
  supported-currencies: BRL,USD,EUR
